// Homeworks/leet-code-clone-angular/src/components/task-view/task-view.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Task, TaskComplexity } from '../../models/Task';
import { delay, tags, tasks } from '../../utils';
import { CommonModule, JsonPipe } from '@angular/common';
import { Tag } from '../../models/Tag';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-task-view',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './task-view.component.html',
  styleUrl: './task-view.component.css'
})
export class TaskViewComponent {
  constructor(
    private readonly router: Router,
    private readonly route: ActivatedRoute
  ){
    const taskId = Number(this.route.snapshot.paramMap.get("id"));
    this.model = tasks.find(x => x.id == taskId) ?? this.model;
  }
  model: Task = new Task(0, "", TaskComplexity.Middle);
  complexities: [string, TaskComplexity][] = Object.entries(TaskComplexity).filter(x => typeof(x[1]) === "number").map(x => [x[0], x[1] as TaskComplexity]);
  tags: Tag[] = tags;
  async save(){
    await delay();
    if (this.model.id == 0){
      this.model.id = tasks[tasks.length - 1].id + 1;
      tasks.push(this.model);
    }
    await this.router.navigate(["/tasks"]);
  }
}

<div class="TaskView">
    <form #taskForm="ngForm" (ngSubmit)="save()">
        <div>
            <label>Название</label>
            <input type="text" required name="name" [(ngModel)]="model.name"/>
        </div>
        <div>
            <label>Сложность</label>
            <select name="complexity" [(ngModel)]="model.complexity">
                @for(complexity of complexities; track complexity[1]){
                    <option [value]="complexity[1]">{{complexity[0]}}</option>
                }
            </select>
        </div>
        <div>
            <label>Тэги</label>
            <select name="tagIds" [(ngModel)]="model.tagIds" multiple>
                @for(tag of tags; track tag.id){
                    <option [value]="tag.id">{{tag.name}}</option>
                }
            </select>
        </div>
        <div>
            <label>Популярность</label>
            <input type="number" name="popularity" [(ngModel)]="model.popularity"/>
        </div>
        <button type="submit" [disabled]="!taskForm.valid">Сохранить</button>
    </form>
</div>

// Homeworks/leet-code-clone-react/src/views/TaskView.tsx
import { ChangeEvent, useEffect, useState } from "react";
import { Task, TaskComplexity } from "../models/Task.model";
import { complexities, delay, tasks } from "../utils/utils";
import { useNavigate, useParams, } from "react-router-dom";

export default function TaskView(){
    const [name, setName] = useState<string>("");
    const [complexity, setComplexity] = useState<TaskComplexity>(TaskComplexity.None);
    const [popularity, setPopularity] = useState<number>(Number.NaN);
    const [code, setCode] = useState<string>("");
    const navigate = useNavigate();
    const { id } = useParams();
    function findComplexity(item: TaskComplexity|number|string|null) : [string, TaskComplexity]{
        return complexities.find(y => y[0] === item || y[1] === item)!;
    }
    function changeComplexity(event: ChangeEvent<HTMLSelectElement>){
        setComplexity(findComplexity(event.target.value)[1]);
    }
    async function save() {
        await delay();
        if (id){
            const task = tasks.find(x => x.id === Number(id))!
            task.name = name;
            task.complexity = complexity;
            task.popularity = popularity;
            task.code = code;
        }
        else
            tasks.push(new Task(tasks.length + 1, name, complexity, popularity, code));
        navigate("/");
    }
    function cancel(){
        navigate("/");
    }
    useEffect(() =>{
        if (id){
            const task = tasks.find(x => x.id === Number(id))!;
            setName(task.name);
            setComplexity(task.complexity);
            setPopularity(task.popularity);
            setCode(task.code);
        }
    }, []);
    return (
        <div>
                <div>
                    <label>Название</label>
                    <input value={name} onChange={x => setName(x.target.value)}></input>
                </div>
                <div>
                    <label>Сложность</label>
                    <select value={findComplexity(complexity)?.[0]??""} onChange={changeComplexity}>{
                        complexities.map(x => <option key={x[1]}>{x[0]}</option>)
                    }</select>
                </div>
                <div>
                    <label>Популярность</label>
                    <input type="number" value={popularity.toString()} onChange={x => setPopularity(Number(x.target.value))}></input>
                </div>
                <div>
                    <label>Код</label>
                    <textarea value={code} onChange={x => setCode(x.target.value)}></textarea>
                </div>
                <div>
                    <button onClick={save}>Сохранить</button>
                    <button onClick={cancel}>Отмена</button>
                </div>
        </div>
    );
}
