// Homeworks/leet-code-clone-react/src/views/UserView.tsx
import { useEffect, useState } from "react";
import { delay, users } from "../utils/utils";
import { User } from "../models/User.model";
import { useNavigate, useParams } from "react-router-dom";

export default function UserView(){
    const [name, setName] = useState<string>("");
    const navigate = useNavigate();
    const { id } = useParams();
    useEffect(() => {
        if (id){
            const user = users.find(x => x.id == Number(id))!;
            setName(user.name);
        }
    }, []);
    async function save() : Promise<void>{
        await delay();
        users.push(new User(users.length + 1, name));
        navigate("/users");
    }
    function cancel() : void {
        navigate("/users");
    }
    return <div>
        <div>
            <label>Имя</label>
            <input value={name} onChange={x => setName(x.target.value)}></input>
        </div>
        <div>
            <button onClick={save}>Сохранить</button>
            <button onClick={cancel}>Отмена</button>
        </div>
    </div>;
}

// Homeworks/leet-code-clone-angular/src/components/user-view/user-view.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { User } from '../../models/User.model';
import { ActivatedRoute, Route, Router } from '@angular/router';
import { delay, users } from '../../utils';
import { CommonModule } from '@angular/common';
import { UserLevel } from '../../models/enums/UserLevel';

@Component({
  selector: 'app-user-view',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './user-view.component.html',
  styleUrl: './user-view.component.css'
})
export class UserViewComponent {
  constructor(
    private readonly router: Router,
    private readonly route: ActivatedRoute
  ){
    const userId = Number(this.route.snapshot.paramMap.get("id"));
    this.model = users.find(x => x.id == userId) ?? this.model;
  }
  model: User = new User();
  levels: [string, UserLevel][] = Object.entries(UserLevel).filter(x => typeof(x[1]) === "number").map(x => [x[0], x[1] as UserLevel]);
  async save(): Promise<void>{
    await delay();
    if (this.model.id == 0){
      this.model.id = users[users.length - 1].id + 1;
      users.push(this.model);
    }
    await this.router.navigate(["/users"]);
  }
}

<div class="UserViewComponent">
    <form #userForm="ngForm" (ngSubmit)="save()">
        <div>
            <label>Имя</label>
            <input type="text" required name="firstName" [(ngModel)]="model.firstName"/>
        </div>
        <div>
            <label>Фамилия</label>
            <input type="text" required name="secondName" [(ngModel)]="model.secondName"/>
        </div>
        <div>
            <label>Имя</label>
            <select name="level" [(ngModel)]="model.level">
                @for(level of levels; track level[1]){
                    <option [value]="level[1]">{{level[0]}}</option>
                }
            </select>
        </div>
        <button type="submit" [disabled]="!userForm.valid">Сохранить</button>
    </form>
</div>
